account_id = "a13a5016df895961431fb659d5d3a635"
kv_namespaces = [
  {binding = "BUNGIE_API", id = "94aaee89b0dd448cb5ad4fb2593a9975", preview_id = "94aaee89b0dd448cb5ad4fb2593a9975"},
  {binding = "DESTINY_2_DEFINITIONS", id = "74f0df8897634be895e79a0a3e22f586", preview_id = "74f0df8897634be895e79a0a3e22f586"},
  {binding = "DESTINY_2_ITEM_DEFINITIONS", id = "1033f6988b394e4e8ed82d9949808f55", preview_id = "1033f6988b394e4e8ed82d9949808f55"},
]
name = "d2-inventory-worker"
type = "javascript"
usage_model = "unbound"
workers_dev = true

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"
