account_id = "a13a5016df895961431fb659d5d3a635"
compatibility_date = "2021-11-25"
kv_namespaces = [
  {binding = "BUNGIE_API", id = "94aaee89b0dd448cb5ad4fb2593a9975", preview_id = "94aaee89b0dd448cb5ad4fb2593a9975"},
]
name = "d2-nightfall-worker"
type = "javascript"
usage_model = "unbound"
workers_dev = true

[dev]
port = 3003

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"
