account_id = "a13a5016df895961431fb659d5d3a635"
kv_namespaces = [
  {binding = "BUNGIE_API", id = "94aaee89b0dd448cb5ad4fb2593a9975", preview_id = "94aaee89b0dd448cb5ad4fb2593a9975"},
]
name = "d2-definitions-crawler"
type = "javascript"
usage_model = "unbound"
workers_dev = true

[dev]
port = 3001

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "D2_DEFINITIONS_OBJECT", class_name = "Destiny2DefinitionsDurableObject"}]

[triggers]
crons = ["1 17 * * *"]
