account_id = "a13a5016df895961431fb659d5d3a635"
kv_namespaces = [
  {binding = "BUNGIE_API", id = "94aaee89b0dd448cb5ad4fb2593a9975", preview_id = "94aaee89b0dd448cb5ad4fb2593a9975"},
  {binding = "DESTINY_2_DEFINITIONS", id = "74f0df8897634be895e79a0a3e22f586", preview_id = "74f0df8897634be895e79a0a3e22f586"},
]
name = "d2-oauth-worker"
type = "javascript"
usage_model = "bundled"
workers_dev = true

[build]
command = "npm install && npm run build"
upload_exclude = ["*.map"]
upload_format = "modules"

[triggers]
crons = ["*/30 * * * *"]
