account_id = "a13a5016df895961431fb659d5d3a635"
kv_namespaces = [
  {binding = "BUNGIE_API", id = "94aaee89b0dd448cb5ad4fb2593a9975", preview_id = "94aaee89b0dd448cb5ad4fb2593a9975"},
  {binding = "DESTINY_2_PGCR", id = "60c98a0c878e44a08f02434de9cbfaa4", preview_id = "60c98a0c878e44a08f02434de9cbfaa4"},
]
name = "d2-meta-worker"
type = "javascript"
usage_model = "bundled"
workers_dev = true

[dev]
port = 3011

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [
  {name = "PGCR_DURABLE_OBJECT", class_name = "D2PostGameCarnageReportObject"}, # Binding to our DurableObjectExample class
]

# [triggers]
# crons = ["*/1 * * * *"]
