account_id = "a13a5016df895961431fb659d5d3a635"
kv_namespaces = [
  {binding = "BUNGIE_API", id = "94aaee89b0dd448cb5ad4fb2593a9975", preview_id = "94aaee89b0dd448cb5ad4fb2593a9975"},
  {binding = "DESTINY_2_PGCR", id = "60c98a0c878e44a08f02434de9cbfaa4", preview_id = "60c98a0c878e44a08f02434de9cbfaa4"},
]
name = "d2-pgcr-worker"
type = "javascript"
usage_model = "unbound"
workers_dev = true

[dev]
port = 3010

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[triggers]
crons = ["0,5,10,15,20,25,30,35,40,45,50,55 * * * *"]
