account_id = "a13a5016df895961431fb659d5d3a635"
compatibility_date = "2021-11-25"
main = "dist/index.mjs"
name = "website-builder-worker"
usage_model = "bundled"
workers_dev = true

kv_namespaces = [
  {binding = "BUNGIE_API", id = "94aaee89b0dd448cb5ad4fb2593a9975", preview_id = "94aaee89b0dd448cb5ad4fb2593a9975"},
]

vars = {ACCOUNT_ID = "a13a5016df895961431fb659d5d3a635", ZONE_ID = "26a980504251839979d2321e3bbad257", PAGES_ID = "the-traveler-times"}

[dev]
port = 3009

[build]
command = "npm install && npm run build"

[triggers]
crons = ["5 * * * *"]
