account_id = "a13a5016df895961431fb659d5d3a635"
name = "website-builder-worker"
type = "javascript"
usage_model = "bundled"
workers_dev = true

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[triggers]
crons = ["*/30 * * * *"]
