account_id = "a13a5016df895961431fb659d5d3a635"
compatibility_date = "2021-11-25"
name = "website-builder-worker"
type = "javascript"
usage_model = "bundled"
workers_dev = true

vars = {ACCOUNT_ID = "a13a5016df895961431fb659d5d3a635", PAGES_ID = "the-traveler-times"}

[dev]
port = 3009

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[triggers]
crons = ["2,32 * * * *"]
